import test from 'node:test';import assert from 'node:assert/strict';
import {compileStory} from '../src/compile.mjs';import {makeModel,resolveEnding} from '../src/model.mjs';
const plan={title:'test',author:'test',chapters:Array.from({length:36},(_,i)=>String(i+1))};
function fixture(){return compileStory({plan,chapters:[{id:1,title:'one',scenes:[{id:'a',paragraphs:[{text:'正文'}],choice:{key:'pick',options:[{id:'yes',label:'是',set:{met:true},reply:[{text:'分支正文'}]},{id:'no',label:'否',set:{met:false},reply:[{text:'另一分支'}]}]},evidence:[{id:'e',text:'物证'}]},{id:'conditional',when:{met:true},paragraphs:[{text:'只能见过才能读'}]}]}]});}
test('compile, conditional scenes, real branches, restore and pending chapter',()=>{for(const option of ['yes','no']){const S=fixture(),M=makeModel(S);let v=M.fresh(),guard=0;while(S.nodes[v.node].kind!=='pending'){assert(++guard<30);const n=S.nodes[v.node];v=M.advance(v,n.kind==='choice'?option:undefined);assert.deepEqual(M.validate(JSON.parse(JSON.stringify(v))),v);}assert.equal(v.evidence.includes('e'),true);assert.equal(v.trail.some(id=>id==='ch1.conditional.p0'),option==='yes');assert.equal(v.flags.met,option==='yes');}});
test('unknown nodes, route rewrites and future decisions rejected; imported flags are rederived',()=>{const M=makeModel(fixture());const fresh=M.fresh();assert.throws(()=>M.validate({...fresh,node:'bad'}));assert.throws(()=>M.validate({...fresh,decisions:{future:'yes'}}));assert.equal(M.validate({...fresh,flags:{endingId:'A'}}).flags.endingId,undefined);});
test('six conclusions derived from concrete preparations without mandatory injury for evidence alone',()=>{
 const complete={roster_workers:true,roster_families:true,external_contact:'both',work_delegated:true,ground_response:true,evidence_outside:true,obligations_sent:true,device_policy:'shutdown'};
 assert.equal(resolveEnding(complete),'A');assert.equal(resolveEnding({...complete,device_policy:'obey'}),'B');assert.equal(resolveEnding({...complete,evidence_outside:false}),'C');assert.equal(resolveEnding({...complete,device_policy:'watch'}),'D');assert.equal(resolveEnding({...complete,departure:'leave'}),'E');assert.equal(resolveEnding({roster_workers:false,ground_response:false,external_contact:'none'}),'F');
});
